### ISSUE TITLE
big if statement

### ISSUE THREAD

**Issue by mrrobrob** [samseedsamseed/CodinGamePowerOfThor#3]
Big if statements across lots of lines with nesting. You should change how this code works to concatenate to the direction string instead. This will resolve this as well as the linked issue of repeating very similar code for each North/South bit.

https://github.com/samseedsamseed/CodinGamePowerOfThor/blob/da3abc23df3754a5755aab417525b7d799a86843/MySolution#L37

**Comment by samseedsamseed** [comment]
I also realised that given the format of compass directions, it's way better to decide North/South first, because that allows the simple use of Write rather than concatenation to print out the direction you want.

**Comment by mrrobrob** [comment]
IMO - concatenation is better. It makes it easier to format your code in 3 sections.

1 - read input
2 - process 
3 - write output

**Comment by samseedsamseed** [comment]
I'm going to do a redo right now!
